name: Docker reg

on:
  push:
    branches: 
    - workers

env:
  DOCKER_TOKEN = ${{ secrets.DOCKER_TOKEN }}
  REF_D_NAME = ${{ vars.REF_D_NAME }}
  SELF_D_NAME = ${{ vars.SELF_D_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.REF_D_NAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      run: docker builx . --name=$REF_D_NAME/$SELF_D_NAME:new

    - name: Push
      run: docker push $REF_D_NAME/$SELF_D_NAME:new
